### ISSUE TITLE
Convert previous country data to work with dropdown

### ISSUE THREAD

**Issue by andrewlimaza** [strangerstudios/pmpro-state-dropdowns#11]
If a user enter's Canada (previously) and activates PMPro State Dropdowns it does not select 'Canada' as the state dropdowns add-on uses abbreviated values such as 'CA' for Canada.

We need to make this backwards compatible.

**Comment by andrewlimaza** [comment]
This will take a bit of work to achieve as user's may countries may have typos etc.

**Comment by mircobabini** [comment]
In my own experience (in Italy, where the province 2 letter code is a must, because of new e-invoice legal format) I had to migrate to the old "user strings" to the new 2 letter code. I used a migration script based on [levenshtein](https://www.php.net/manual/en/function.levenshtein.php). It worked automatically 99%, not bad.

By the way, it should work this way I think:
1) show an additional option for old value if not in 2-letter codes list;
2) add the migration script to auto-fix where possible and permit the user to manually complete the 1% undefinable
